### PR TITLE
fix: formatting issues with ksec/ksecn

### PR DESCRIPTION
**Pull request by eshepelyuk**
Hi

The issue is better visible on screenshot

image

### CODE REVIEW

**Comment by kron4eg** [comment]
I’m not sure about this. If you’d pipe the result somewhere, you'll get wrong result, silently.

**Comment by xrstf** [comment]
@kron4eg is the resident expert and IIRC also uses fubectl much more than me, so I trust your decision :-)

**Comment by eshepelyuk** [comment]
@kron4eg you're right, declining it.

**Pull request closed without merging**
