### PR TITLE
Explicit dependency on kubectl plugins in README.md

### PR DESCRIPTION
**Pull request by dharapvj**

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@dharapvj 

`kubectl-view-secret` is not used anymore 

Check commit https://github.com/kubermatic/fubectl/commit/f47df1ac5f39ae5af93e93c9cc1ce535ed7021f2

**Comment by dharapvj** [comment]
> 
> 
> @dharapvj
> 
> `kubectl-view-secret` is not used anymore
> 
> Check commit [f47df1a](https://github.com/kubermatic/fubectl/commit/f47df1ac5f39ae5af93e93c9cc1ce535ed7021f2)

Aah Damn.. sorry I only looked into my local fubectl copy. Ok.. I will revert that commit out.

**Comment by dharapvj** [comment]
Done... removed the view-secret dependency mention.

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
