### PR TITLE
feat: kubectl get/decribe aliases with completion

### PR DESCRIPTION
**Pull request by eshepelyuk**
Inspired by work of https://github.com/msgongora
in https://github.com/msgongora/fubectl

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@msgongora FYI

**Comment by msgongora** [comment]
Hi @eshepelyuk, I deprecated this completion function since I migrated my shell to Zsh, and the alias completion came out of the box in this shell. I would suggest testing this in Zsh. In the function you could do something like `[[ -n "$ZSH_VERSION" ]] && return 0`

**Comment by eshepelyuk** [comment]
Hello all

Is there any feedback on this ?

Regarding `zsh` - I have no possibility to setup `zsh` and research the PR behaviour in `zsh`. I will be appreciated if someone could test this in that shell. But I can conditionally enable this PR only for bash, so `zsh` users won't be affected.

**Comment by kron4eg** [comment]
I'm not sure I understand completely what's happening there

**Comment by eshepelyuk** [comment]
> I'm not sure I understand completely what's happening there

Hello @kron4eg 
I've added more `kubectl` aliases for common operations, providing them with autocompletion function, that was implemented by @msgongora in his own fork.

**Pull request closed without merging**
