### PR TITLE
feat: separate aliases scope to current NS and entire cluster

### LINKED ISSUE #70: Consider separate aliases for current NS and all NS
Hello

Currently many aliases are querying resources from all namespaces. In case of big cluster with dozens NS and dozens of pods in evey NS such frequent querying could affect cluster performance and also provide slow response time to end users.

I propose to introduce one of the following
* config parameter (env var, file) that changes namespace filtering behaviour of all declared aliases
* duplicate aliases to have 2 commands 
    * `klog` for current namespace
    * `kloga` for all namespaces
    * For backward compatibility it could be `klog` for current behaviour (all NS) and `klg` for current NS

Wdyt ?

### PR DESCRIPTION
**Pull request by eshepelyuk**
Resolves #70

Signed-off-by: Ievgenii Shepeliuk <eshepelyuk@gmail.com>

### CODE REVIEW

**Comment by eshepelyuk** [comment]
@scheeles @kron4eg any feedback plz ?

**Comment by kron4eg** [comment]
While I like this, I really dislike the chaos in names. There is no structure/system in naming. Just an example: we can have a `command1` for whole cluster and `command1cn` for current namespace (cn = mnemonic).

**Comment by eshepelyuk** [comment]
> While I like this, I really dislike the chaos in names. There is no structure/system in naming. Just an example: we can have a `command1` for whole cluster and `command1cn` for current namespace (cn = mnemonic).

So, please suggest one of following to proceed with the PR

1. better names for affected functions
1. drop backward compatibility and embrace convention: `klog` - for current NS, `kloga` - for cluster wide
1. decline this PR

**Comment by kron4eg** [comment]
@eshepelyuk Id go with the 1 option.

**Comment by eshepelyuk** [comment]
> @eshepelyuk Id go with the 1 option.

Ok great, so I am waiting for function names suggestions.
In fact, you could edit this PR yourself, writing down preferred names.

**Comment by kron4eg** [comment]
Let's see how "original-all-cluster-command"+"n" will look like.

kwatch -> kwatchn
ked -> kedn
kdes -> kdesn
kdel -> kdeln
kex -> kexn
kfor -> kforn
ktree -> ktreen
ksec -> ksecn

**Comment by eshepelyuk** [comment]
Great idea,letme apply it :)

**Comment by eshepelyuk** [comment]
@kron4eg suggestions applied.

**Review by kron4eg — APPROVED** [review]
/approve

**Pull request merged**
